app/user/forms.py
"""
Controls forms for user control
"""
from sqlalchemy.sql import text
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed, FileRequired
from flask_login import current_user
from wtforms import StringField, SubmitField, BooleanField
from wtforms.validators import ValidationError, DataRequired, Email
from app import db, avatar_uploads
from app.database.models import User

class DeleteUserForm(FlaskForm):
    """Deletes the user"""
    password = StringField('Your Password', validators=[DataRequired()])
    check = StringField('To verify, type "delete my account" below', validators=[DataRequired()])
    submit = SubmitField('Delete Account')

    def validate_password(self, password):
        """Checks if the password entered is correct"""
        if not current_user.check_password(password.data):
            raise ValidationError('Incorrect Password')

    def validate_check(self, check):
        """Checks if """
        if check.data != "delete my account":
            raise ValidationError("Not typed correctly")

class EditProfileForm(FlaskForm):
    """Allows profile editing"""
    name = StringField('Name', validators=[DataRequired()])
    organisation = StringField('Organisation', validators=[DataRequired(
        message="If not appliable use N/A")], description="If not appliable use N/A")
    username = StringField('Username')
    email = StringField('Email', validators=[DataRequired(), Email()])
    admin = BooleanField("Is Admin?")
    reviewer = BooleanField("Is Reviewer?")
    submit = SubmitField('Edit Profile')

    def __init__(self, original_username, original_email, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.original_username = original_username
        self.original_email = original_email

    def validate_username(self, username):
        """Checks if username is already used unless its current username"""
        if username.data != self.original_username:
            query = text("SELECT id, username FROM user WHERE username = :username LIMIT 1 OFFSET 0")
            user = db.session.query(User).from_statement(query).params(username=self.username.data).first()
            if user is not None:
                raise ValidationError('Please use a different username.')

    def validate_email(self, email):
        """Checks if email is already used unless its current email"""
        if email.data != self.original_email:
            query = text("SELECT id, email FROM user WHERE email = :email LIMIT 1 OFFSET 0")
            user = db.session.query(User).from_statement(query).params(email=self.email.data).first()
            if user is not None:
                raise ValidationError('Please use a different email address.')

class UploadAvatarForm(FlaskForm):
    """Upload an Avatar"""
    avatar = FileField('Avatar', validators=[FileRequired(), FileAllowed(avatar_uploads, 'Images only!')])
    submit = SubmitField('Upload Avatar')

app/user/__init__.py
"""
Initialises User
"""
from flask import Blueprint

bp = Blueprint('user', __name__)

from app.user import routes

app/user/routes.py
"""
Controls which pages load and what is shown on each
"""
from os import path, remove
from sqlalchemy.sql import text
from flask import (render_template, flash, redirect, url_for, request, send_from_directory,
                   current_app, abort)
from flask_login import current_user, login_required
from werkzeug.utils import secure_filename
from arrow import get as arrowGet
from app import db, avatar_uploads
from app.database.models import User, Submission
from app.user import bp
from app.user.forms import DeleteUserForm, EditProfileForm, UploadAvatarForm

def check_permissions(username):
    """Checks if can edit users"""
    if not current_user.username == username:
        abort(403)

@bp.route('/<username>/')
@login_required
def user_profile(username):
    """Makes dynamic user pages"""
    query = text("SELECT id, username, name, last_seen FROM user WHERE username = :username LIMIT 1 OFFSET 0")
    user = db.session.query(User).from_statement(query).params(username=username).first_or_404()
    # Below not changed to raw SQL as timestamp becomes a string not a datetime type
    submissions = Submission.query.filter_by(user_id=user.id).order_by(Submission.timestamp.desc()).all()
    timestamp = arrowGet(user.last_seen).humanize()
    return render_template('users/user.html', title=user.username, user=user,
                           submissions=submissions, last_seen=timestamp)

@bp.route('/<username>/avatar')
def avatar(username):
    """Gets avatar if one is set else uses default"""
    user = db.session.execute('SELECT avatar FROM user WHERE username = :username LIMIT 1 OFFSET 0',
                              {'username': username}).fetchone()
    if user.avatar == "":
        return redirect("https://www.gravatar.com/avatar?d=identicon&s=128")
    return send_from_directory(
        current_app.config['UPLOADS_DEFAULT_DEST'] + "avatars/", user.avatar)

@bp.route('/<username>/delete_account', methods=['GET', 'POST'])
@login_required
def delete_account(username):
    """Allows to delete the user"""
    check_permissions(username)
    form = DeleteUserForm()
    if form.validate_on_submit():
        query = text("SELECT * FROM user WHERE username = :username LIMIT 1 OFFSET 0")
        user = db.session.query(User).from_statement(query).params(username=username).first()
        query = text("SELECT * FROM submission WHERE user_id = :user_id")
        submissions = db.session.query(Submission).from_statement(query).params(user_id=user.id).all()
        if user is not None:
            for _, submission in enumerate(submissions):
                db.session.delete(submission)
            db.session.delete(user)
            db.session.commit()
            flash("Successfully deleted user and linked submissions")
            return redirect(url_for('home.index'))
        flash("User not found", 'error')
    return render_template('users/delete_account.html', title='Account Deletion', form=form)

@bp.route('/<username>/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile(username):
    """Profile edit page"""
    check_permissions(username)
    form = EditProfileForm(current_user.username, current_user.email)
    form.username.render_kw = {'disabled': 'disabled'}
    form.admin.render_kw = {'disabled': 'disabled'}
    form.reviewer.render_kw = {'disabled': 'disabled'}
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.organisation = form.organisation.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your changes have been saved.')
        return redirect(url_for('user.edit_profile', username=current_user.username))
    elif request.method == 'GET':
        form.name.data = current_user.name
        form.organisation.data = current_user.organisation
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.admin.data = current_user.admin
        form.reviewer.data = current_user.reviewer
    return render_template('users/edit_profile.html', title='Edit Profile', form=form)

@bp.route('/<username>/upload_avatar', methods=['GET', 'POST'])
@login_required
def upload_avatar(username):
    """Controls avatar uploads"""
    check_permissions(username)
    form = UploadAvatarForm()
    if request.method == 'POST' and 'avatar' in request.files:
        if form.validate_on_submit():
            query = text("SELECT id, avatar FROM user WHERE username = :username LIMIT 1 OFFSET 0")
            user = db.session.query(User).from_statement(query).params(username=username).first()
            if (user.avatar != "") and (path.exists(
                    current_app.config['UPLOADS_DEFAULT_DEST'] + "avatars/" + user.avatar)):
                remove(current_app.config['UPLOADS_DEFAULT_DEST'] + "avatars/" + user.avatar)
                user.avatar_filename("")
            file_obj = request.files['avatar']
            file_extension = (file_obj.filename.split('.')[-1]).lower()
            file_name = secure_filename(current_user.username + '.' + file_extension)
            file_name = avatar_uploads.save(file_obj, name=file_name)
            user.avatar_filename(file_name)
            db.session.commit()
            flash('Avatar updated')
            return redirect(url_for('user.user_profile', username=current_user.username))
        flash('Avatar not uploaded', 'error')
    return render_template('users/upload_avatar.html', title='Upload Avatar', form=form)

app/templates/users/_submission.html
<a class="list-group-item list-group-item-action text-reset px-0" href="{{ url_for('competition.submission_page', comp_id=submission.comp_id, cat_id=submission.categories[0].id, sub_id=submission.id) }}">
    <div class="d-flex w-100 justify-content-between">
        <h4 class="mb-1">{{ submission.name }}</h4>
        <small>{{ submission.timestamp.strftime('%Y-%m-%d %H:%M:%S') }}</small>
    </div>
    <p class="mb-1">{{ submission.body }}</p>
</a>

app/templates/users/delete_account.html
{% extends "base.html" %}
{% import '_wtf.html' as wtf %}

{% block app_content %}
    <h1>{{ title }}</h1>
    <h5>This will remove your account and any associated submissions</h5>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form, button_map={'submit':'outline-danger'}) }}
        </div>
    </div>
{% endblock %}

app/templates/users/edit_profile.html
{% extends "base.html" %}

{% block app_content %}
    {% include '_form.html' %}
    <br>
    <p><a href="{{ url_for('user.upload_avatar', username=current_user.username) }}">Upload Avatar</a></p>
    <p><a href="{{ url_for('auth.change_password') }}">Change Password</a></p>
    <p><a href="{{ url_for('user.delete_account', username=current_user.username) }}">Delete Account</a></p>
{% endblock %}

app/templates/users/login.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    {% include '_form.html' %}
    <br>
    <p>New User? <a href="{{ url_for('register') }}">Click to Register!</a></p>
{% endblock %}

app/templates/users/upload_avatar.html
{% extends "base.html" %}

{% block app_content %}
    {% include '_form.html' %}
    <br>
    <p>There is a max size limit of {{ config['MAX_UPLOAD_SIZE'] }}MiB</p>
    <p>Please ensure it is a square</p>
{% endblock %}

app/templates/users/user.html
{% extends "base.html" %}

{% block scripts %}
{{super()}}
<script src="/static/js/initialiseTooltip.min.js" integrity="sha384-dX23tlcG96awOEcssN/7WL2CN6J9qMY+tc4H2g13XLot37bTz1bbwqlg0+1fuXr+" crossorigin="anonymous" defer></script>
{% endblock %}

{% block app_content %}
    <div class="media row mt-3">
        <div class="col-5 col-sm-3">
            <img class="w-100 h-100 border p-0" src="{{ user.avatar_get() }}">
        </div>
        <div class="media-body col-7 col-sm-9">
            <h1><a href="#" class="text-reset text-decoration-none" data-toggle="tooltip" data-placement="top" title="{{ user.username }}">{{ user.name }}</a></h1>
            {% if last_seen %}
                <p>Last seen: <a href="#" class="text-reset text-decoration-none" data-toggle="tooltip" data-placement="top" title="{{ user.last_seen }}">{{ last_seen }}</a></p>
            {% endif %}
            {% if user == current_user %}
                <p><a href="{{ url_for('user.edit_profile', username=current_user.username) }}">Edit your profile</a></p>
            {% endif %}
        </div>
    </div>
    <br>
    <h2>Submissions</h2>
    <div class="list-group list-group-flush">
        {% for submission in submissions %}
            {% include 'users/_submission.html' %}
        {% endfor %}
    </div>
{% endblock %}