app/competition/forms.py
"""
Controls forms in competitions
"""
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed, FileRequired
from wtforms import StringField, SubmitField, TextAreaField, BooleanField, IntegerField
from wtforms.validators import DataRequired, Length, NumberRange
from app import submission_uploads

class CompetitionForm(FlaskForm):
    """Creates or edits a Competition"""
    name = StringField('Name', validators=[DataRequired(), Length(min=1, max=64)])
    body = TextAreaField('Body', validators=[DataRequired(), Length(min=1, max=280)])
    submit = SubmitField('Submit')

class CategoryForm(FlaskForm):
    """Creates or edits a Category"""
    name = StringField('Name', validators=[DataRequired(), Length(min=1, max=64)])
    body = TextAreaField('Body', validators=[DataRequired(), Length(min=1, max=280)])
    submit = SubmitField('Submit')

class SubmissionForm(FlaskForm):
    """Creates or edits a Submission"""
    name = StringField('Name', validators=[DataRequired(), Length(min=1, max=64)])
    body = TextAreaField('Body', validators=[DataRequired(), Length(min=1, max=10000)])
    submit = SubmitField('Submit')


def submission_edit_categories_form(submission, categories):
    """Generates form"""
    for _, category in enumerate(categories):
        if submission.check_category(category.id) == 1:
            passed = "checked"
        else:
            passed = ""
        setattr(BlankForm, str(category.id), BooleanField(category.name, default=passed))
    BlankForm.submit = SubmitField('Submit')
    return BlankForm()

class SubmissionUploadForm(FlaskForm):
    """Upload an Avatar"""
    fileUpload = FileField('File', validators=[FileRequired(), FileAllowed(
        submission_uploads, 'File type not allowed')])
    submit = SubmitField('Upload File')

class SubmissionVotingForm(FlaskForm):
    """Upload an Avatar"""
    score = IntegerField('Score', validators=[NumberRange(min=0, max=10)])
    comment = TextAreaField('Comment', validators=[DataRequired(), Length(min=1, max=10000)])
    submit = SubmitField('Vote')

class BlankForm(FlaskForm):
    """Supposed to be blank"""

app/competition/__init__.py
"""
Initialises Main Part
"""
from flask import Blueprint

bp = Blueprint('competition', __name__)

from app.competition import competition, category, submission, files

app/competition/routes.py
"""
Controls which pages load and what is shown on each
"""
from arrow import get as arrowGet
from flask import render_template, flash, redirect, url_for, abort, request, current_app, send_from_directory, make_response
from flask_login import current_user, login_required
from markdown import markdown
from bleach import clean
from bleach_whitelist import markdown_tags, markdown_attrs
from werkzeug.utils import secure_filename
from app import db, review_uploads
from app.database.models import Competition, Category, Review, ReviewUploads, User, Votes
from app.competition import bp
from app.competition.forms import (CompetitionCreateForm, CategoryCreateForm, ReviewCreateForm,
                                   ReviewEditForm, ReviewUploadForm, review_edit_categories_form, ReviewVotingForm)

@bp.route('/')
@login_required
def index():
    """Makes dynamic page listing all competitions"""
    comps = [competition.to_json() for competition in Competition.query.all()]
    return render_template('competition/index.html', title="Competitions", competitions=comps)

@bp.route('/create', methods=['GET', 'POST'])
@login_required
def competition_create():
    """Creates competitions"""
    form = CompetitionCreateForm()
    if form.validate_on_submit():
        competition = Competition(name=form.name.data,
                                  body=form.body.data
                                 )
        db.session.add(competition)
        db.session.commit()
        flash('Competition created successfully')
        return redirect(url_for('competition.competition_overview', comp_id=competition.id))
    return render_template('competition/competitionCreate.html', title='Competition Create', form=form)

@bp.route('/file/<uuid>/<filename>')
@login_required
def file_download(uuid, filename):
    """Sends file"""
    if not secure_filename(uuid) == uuid:
        abort(404)
    uploads = ReviewUploads.query.filter_by(uuid=uuid).first_or_404()
    if not filename == uploads.filename:
        abort(404)
    r = make_response(send_from_directory(current_app.config['UPLOADS_DEFAULT_DEST'] + "reviews/", uuid))
    r.headers['Content-Disposition'] = 'attachment; filename="{0}"'.format(filename)
    return r

@bp.route('/<int:comp_id>')
@login_required
def competition_overview(comp_id):
    """Makes dynamic competition pages"""
    competition = Competition.query.filter_by(id=comp_id).first_or_404()
    categories = [category.to_json() for category in Category.query.filter_by(comp_id=comp_id)]
    return render_template('competition/competition.html', title=competition.name, name=competition.name,
                           body=competition.body, categories=categories, id=comp_id)

@bp.route('/<int:comp_id>/create', methods=['GET', 'POST'])
@login_required
def category_create(comp_id):
    """Create categories"""
    form = CategoryCreateForm()
    if form.validate_on_submit():
        category = Category(name=form.name.data,
                            body=form.body.data,
                            comp_id=comp_id
                            )
        db.session.add(category)
        db.session.commit()
        flash('Category created successfully')
        return redirect(url_for('competition.category_overview', comp_id=comp_id, cat_id=category.id))
    return render_template('competition/categoryCreate.html', title='Category Create', form=form)

@bp.route('/<int:comp_id>/<int:cat_id>')
@login_required
def category_overview(comp_id, cat_id):
    """Makes dynamic categories pages"""
    category = Category.query.filter_by(id=cat_id).filter_by(comp_id=comp_id).first_or_404()
    reviews = Review.query.filter_by(comp_id=comp_id).all()
    cat_reviews = []
    for _, review in enumerate(reviews):
        for j in range(len(review.categories)):
            if review.categories[j].id == cat_id:
                cat_reviews.append(review.to_json())

    return render_template('competition/category.html', title=category.name, name=category.name,
                           body=category.body, reviews=cat_reviews, comp_id=comp_id, cat_id=cat_id)

@bp.route('/<int:comp_id>/<int:cat_id>/create', methods=['GET', 'POST'])
@login_required
def review_create(comp_id, cat_id):
    """Create reviews"""
    form = ReviewCreateForm()
    if form.validate_on_submit():
        review = Review(name=form.name.data,
                        body=form.body.data,
                        user_id=int(current_user.id),
                        comp_id=int(comp_id)
                        )
        db.session.add(review)
        category = Category.query.filter_by(id=cat_id).filter_by(comp_id=comp_id).first_or_404()
        review.categories.append(category)
        db.session.commit()

        flash('Review created successfully')
        return redirect(url_for('competition.review_overview',
                                comp_id=comp_id, cat_id=cat_id, review_id=review.id))
    return render_template('competition/reviewCreate.html', title='Review Create', form=form)

@bp.route('/<int:comp_id>/<int:cat_id>/<int:review_id>')
@login_required
def review_overview(comp_id, cat_id, review_id):
    """Makes dynamic review pages"""
    review = Review.query.filter_by(id=review_id).filter_by(comp_id=comp_id).first_or_404()
    if not review.check_category(cat_id):
        abort(404)
    body = markdown(review.body, output_format="html5")
    body = clean(body, markdown_tags, markdown_attrs)
    user = User.query.filter_by(id=review.user_id).first_or_404()
    timestamp = arrowGet(review.timestamp).humanize()
    uploadsCount = ReviewUploads.query.filter_by(review_id=review_id).count()
    owner = current_user.id == user.id
    return render_template('competition/review.html', title=review.name, review=review,
                           body=body, user=user, cat_id=cat_id, humanTime=timestamp,
                           uploadsCount=uploadsCount, owner=owner)

@bp.route('/<int:comp_id>/<int:cat_id>/<int:review_id>/delete', methods=['GET', 'POST'])
@login_required
def review_delete(comp_id, cat_id, review_id):
    """Deletes the review"""
    review = Review.query.filter_by(id=review_id).filter_by(comp_id=comp_id).first_or_404()
    if not review.check_category(cat_id):
        abort(404)
    if int(current_user.id) != int(review.user_id):
        abort(403)
    db.session.delete(review)
    db.session.commit()
    flash('Review deleted successfully')
    return redirect(url_for('competition.category_overview', comp_id=comp_id, cat_id=cat_id))

@bp.route('/<int:comp_id>/<int:cat_id>/<int:review_id>/edit', methods=['GET', 'POST'])
@login_required
def review_edit(comp_id, cat_id, review_id):
    """Edits the review"""
    review = Review.query.filter_by(id=review_id).filter_by(comp_id=comp_id).first_or_404()
    form = ReviewEditForm()
    if not review.check_category(cat_id):
        abort(404)
    if int(current_user.id) != int(review.user_id):
        abort(403)
    if request.method == 'GET':
        form.name.data = review.name
        form.body.data = review.body
    if form.validate_on_submit():
        review.name = form.name.data
        review.body = form.body.data
        db.session.commit()

        flash('Review edited successfully')
        return redirect(url_for('competition.review_overview',
                                comp_id=comp_id, cat_id=cat_id, review_id=review.id))
    return render_template('competition/reviewEdit.html', title='Review Edit', form=form)

@bp.route('/<int:comp_id>/<int:cat_id>/<int:review_id>/edit/categories', methods=['GET', 'POST'])
@login_required
def review_edit_category(comp_id, cat_id, review_id):
    """Allows assigning categories"""
    review = Review.query.filter_by(id=review_id).filter_by(comp_id=comp_id).first_or_404()
    categories = Category.query.filter_by(comp_id=comp_id)
    form = review_edit_categories_form(review, categories)
    if not review.check_category(cat_id):
        abort(404)
    if int(current_user.id) != int(review.user_id):
        abort(403)
    if request.method == 'GET':
        return render_template('competition/reviewCategoryEdit.html', title='Edit Category', form=form)
    if form.validate_on_submit():
        for _, checkbox in enumerate(form):
            try:
                int(checkbox.name)
            except ValueError:
                break
            else:
                if review.check_category(int(checkbox.name)) != checkbox.data:
                    category = Category.query.filter_by(id=int(checkbox.name)).filter_by(comp_id=comp_id).first_or_404()
                    if checkbox.data:
                        review.categories.append(category)
                    else:
                        review.categories.remove(category)
        db.session.commit()
        flash('Review Categories updated successfully')
        return redirect(url_for('competition.competition_overview', comp_id=comp_id))

@bp.route('/<int:comp_id>/<int:cat_id>/<int:review_id>/upload', methods=['GET', 'POST'])
@login_required
def review_upload(comp_id, cat_id, review_id):
    """Allow documents to be uploaded"""
    review = Review.query.filter_by(id=review_id).filter_by(comp_id=comp_id).first_or_404()
    form = ReviewUploadForm()
    if not review.check_category(cat_id):
        abort(404)
    if int(current_user.id) != int(review.user_id):
        abort(403)
    if request.method == 'POST' and 'fileUpload' in request.files:
        if form.validate_on_submit():
            uploads = ReviewUploads.query.order_by(ReviewUploads.id.desc()).filter_by(review_id=review_id).first()
            if uploads is None:
                next_id = 1
            else:
                next_id = uploads.id+1 #ids are per review
            file_obj = request.files['fileUpload']
            file_name = secure_filename(file_obj.filename)
            uploads = ReviewUploads(id=next_id,
                                    filename=file_name,
                                    review_id=int(review_id))

app/templates/competition/category.html
{% extends "base.html" %}

{% block scripts %}
{{super()}}
<script src="/static/js/initialiseTooltip.min.js" integrity="sha384-dX23tlcG96awOEcssN/7WL2CN6J9qMY+tc4H2g13XLot37bTz1bbwqlg0+1fuXr+" crossorigin="anonymous" defer></script>
{% endblock %}

{% block styles %}
{{super()}}
<!--Font Awesome-->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css" integrity="sha384-KA6wR/X5RY4zFAHpv/CnoG2UW1uogYfdnP67Uv7eULvTveboZJg0qUpmJZb5VqzN" crossorigin="anonymous">
{% endblock %}

{% block app_content %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ url_for('competition.competitions_overview') }}">Competitions</a></li>
        <li class="breadcrumb-item"><a href="{{ url_for('competition.categories_overview', comp_id=comp_id) }}">{{ comp_name }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ name }}</li>
        </ol>
    </nav>
    <h1>{{ name }}</h1>
    <p>{{ body }}</p>
    <br>
    <h4>Submissions</h4>
    <div class="card-columns">
    {% set count = 0 %}
    {% for submission in submissions %}
        <a class="text-reset" href="{{ url_for('competition.submission_page', comp_id=submission.comp_id, cat_id=cat_id, sub_id=submission.id) }}">
            <div class="card"><div class="card-body">
                <h5 class="card-title">{{ submission.name }}</h5>
                <div class="card-text mb-1"><small class="text-muted">
                    <a href="#" class="text-reset text-decoration-none" data-toggle="tooltip" data-placement="top" title="{{ submission.timestamp }}">Last updated {{ submission.humantime }}</a>
                    {% if admin %}
                        <div class="rating mb-1">
                            {% set vars = {'scoreToGo': (scores[loop.index-1][0] / 2), 'count': 5} %}
                            {% for i in range(vars.scoreToGo|round(0, 'floor')|int) %}
                                {% if vars.update({'scoreToGo': vars.scoreToGo - 1}) %}{% endif %}
                                {% if vars.update({'count': vars.count - 1}) %}{% endif %}
                                <i class="fas fa-star"></i>
                            {% endfor %}
                            {% if vars.scoreToGo|round(1) >= 0.5 %}
                                {% if vars.update({'count': vars.count - 1}) %}{% endif %}
                                <i class="fas fa-star-half-alt"></i>
                            {% endif %}
                            {% for i in range(vars.count) %}
                                <i class="far fa-star"></i>
                            {% endfor %}
                            {{ scores[loop.index-1][0]|round(1) }}
                            <span class="text-muted">From {{ scores[loop.index-1][1] }} votes</span>
                        </div>
                    {% endif %}
                </small></div>
            </div></div>
        </a>
    {% endfor %}
    </div>
    <br>
    <p><a href="{{ url_for('competition.submission_create', comp_id=comp_id, cat_id=cat_id) }}">Create Submission</a></p>
    {% if admin %}
        <p><a href="{{ url_for('competition.category_edit', comp_id=comp_id, cat_id=cat_id) }}">Edit Category</a></p>
    {% endif %}
{% endblock %}

app/templates/competition/categoryCreate.html
{% extends "base.html" %}

{% block app_content %}
    {% include '_form.html' %}
{% endblock %}

app/templates/competition/categoryEdit.html
{% extends "base.html" %}

{% block app_content %}
    {% include '_form.html' %}
{% endblock %}

app/templates/competition/competition.html
{% extends "base.html" %}

{% block app_content %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ url_for('competition.competitions_overview') }}">Competitions</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ competition.name }}</li>
        </ol>
    </nav>
    <h1>{{ competition.name }}</h1>
    <p>{{ competition.body }}</p>
    <p class="mb-0">The same submission can enter multiple categories.</p>
    <details>
        <summary>How to do this</summary>
        <div>
            After submitting your submission, go to edit it.
            From their choose the change categories button.
            This gives you a list of all the categories in this competition.
            Select the categories you wish to enter.
        </div>
    </details>
    <br>
    <h4>Categories</h4>
    <div class="list-group list-group-flush">
    {% for category in categories|sort(attribute='name') %}
        <a class="list-group-item list-group-item-action" href="{{ url_for('competition.submissions_overview', comp_id=category.comp_id, cat_id=category.id) }}">
            <p class="mb-1 list-group-object-name">{{ category.name }}</p>
            <small class="text-muted">{{ category.body }}</small>
        </a>
    {% endfor %}
    </div>
    <br>
    {% if admin %}
        <p><a href="{{ url_for('competition.category_create', comp_id=id) }}">Create Category</a></p>
        <p><a href="{{ url_for('competition.competition_edit', comp_id=id) }}">Edit Competition</a></p>
    {% endif %}
{% endblock %}

app/templates/competition/competitionEdit.html
{% extends "base.html" %}

{% block app_content %}
    {% include '_form.html' %}
{% endblock %}

app/templates/competition/index.html
{% extends "base.html" %}

{% block app_content %}
    <h1>Competitions</h1>
    <p>
        List of all the Competitions available<br>
        Please choose the competition you wish to enter
    </p>
    <div class="list-group list-group-flush">
    {% for competition in competitions %}
        <a class="list-group-item list-group-item-action" href="{{ url_for('competition.categories_overview', comp_id=competition.id) }}">
            <p class="mb-1 list-group-object-name">{{ competition.name }}</p>
            <small class="text-muted">{{ competition.body }}</small>
        </a>
    {% endfor %}
    </div>
    <br>
    {% if admin %}
        <p><a href="{{ url_for('competition.competition_create') }}">Create Competition</a></p>
    {% endif %}
{% endblock %}

app/templates/competition/reviewCategoryEdit.html
{% extends "base.html" %}

{% block app_content %}
    {% include '_form.html' %}
{% endblock %}

app/templates/competition/reviewCreate.html
{% extends "base.html" %}

{% block styles %}
{{super()}}
<!-- SimpleMDE -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/simplemde@1.11.2/dist/simplemde.min.css" integrity="sha384-rQdIropf4eQBEB9SkNB4xxukYHlkyXJfKYkpVNUQOLizz+d2q0wo7zjVA2XcYSij" crossorigin="anonymous">
{% endblock %}
{% block scripts %}
{{super()}}
<!-- SimpleMDE -->
<script src="https://cdn.jsdelivr.net/npm/simplemde@1.11.2/dist/simplemde.min.js" integrity="sha384-83rBTICYr+FwAC+A5t0ZYsWjTcPXibCe/NBSFLAgMPkwHBvIi02EcE9OShMsGCi3" crossorigin="anonymous" async></script>
<script src="/static/js/initialiseSimpleMDE.min.js" integrity="sha384-UaqFLTmSfnRaybf+J9i9rjTSpiB07Clnynva1XZCpuTsj2bNnkHKQHjqtIx22Rkq" crossorigin="anonymous" async defer></script>
{% endblock %}

{% block app_content %}
    {% include '_form.html' %}
{% endblock %}

app/templates/competition/reviewUpload.html
{% extends "base.html" %}

{% block app_content %}
    {% include '_form.html' %}
    <br>
    <p>There is a max size limit of {{ config['MAX_UPLOAD_SIZE'] }}MiB</p>
{% endblock %}

app/templates/competition/reviewVoting.html
{% extends "base.html" %}
{% import '_wtf.html' as wtf %}

{% block app_content %}
    <div class="row">
        <div class="col-md-4">
            <h1>{{ review.name }} - {{ title }}</h1>
            {{ wtf.quick_form(form) }}
        </div>
        <div class="col">
            <h3>Category</h3>
            <h5>{{ cat.name }}</h5>
            <p class="font-weight-light">{{ cat.body }}</p>
        </div>
    </div>
{% endblock %}

app/templates/competition/submission.html
{% extends "base.html" %}

{% block scripts %}
{{super()}}
<script src="/static/js/initialiseTooltip.min.js" integrity="sha384-dX23tlcG96awOEcssN/7WL2CN6J9qMY+tc4H2g13XLot37bTz1bbwqlg0+1fuXr+" crossorigin="anonymous" defer></script>
{% endblock %}

{% block app_content %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ url_for('competition.competitions_overview') }}">Competitions</a></li>
        <li class="breadcrumb-item"><a href="{{ url_for('competition.categories_overview', comp_id=submission.comp_id) }}">{{ comp_name }}</a></li>
        <li class="breadcrumb-item"><a href="{{ url_for('competition.submissions_overview', comp_id=submission.comp_id, cat_id=cat_id) }}">{{ cat_name }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ submission.name }}</li>
        </ol>
    </nav>
    {% if (not uploadsCount|int == 0) or current_user.admin %}
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" id="submission-tab" href="{{ url_for('competition.submission_page', comp_id=submission.comp_id, cat_id=cat_id, sub_id=submission.id) }}">
                Submission
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="uploads-tab" href="{{ url_for('competition.submission_files', comp_id=submission.comp_id, cat_id=cat_id, sub_id=submission.id) }}">
                Uploads <span class="badge badge-light">{{ uploadsCount }}</span>
            </a>
        </li>
        {% if current_user.admin %}
            <li class="nav-item">
                <a class="nav-link" id="votes-overview-tab" href="{{ url_for('competition.submission_vote_overviewer', comp_id=submission.comp_id, cat_id=cat_id, sub_id=submission.id) }}">
                    Votes Overview
                </a>
            </li>
        {% endif %}
    </ul>
    <br>
    {% endif %}
    <div class="text-center">
        <small><a href="#" class="text-muted text-decoration-none text-uppercase letter-spacing-2" data-toggle="tooltip" data-placement="top" title="{{ submission.timestamp }}">{{ humanTime }}</a></small>
        <h1 class="display-4 text-break">{{ submission.name }}</h1>
        <a class="text-muted text-decoration-none text-uppercase text-uppercase letter-spacing-2" href="{{ url_for('user.user_profile', username=user.username) }}">
            <img class="rounded-circle border mr-2" height="45px" width="45px" src="{{ submission.author.avatar_get() }}" />
            <small>{{ user.name }}</small>
        </a>
    </div>
    <br>
    {{ body|safe }}
    <div class="row text-muted justify-content-center text-lg-center">
        {% if owner %}
        <div class="col">
            <div class="btn-group" role="group" aria-label="Change Submission">
                <a href="{{ url_for('competition.submission_edit', comp_id=submission.comp_id, cat_id=cat_id, sub_id=submission.id) }}" role="button" class="btn btn-outline-primary">Edit</a>
                <a href="{{ url_for('competition.submission_upload', comp_id=submission.comp_id, cat_id=cat_id, sub_id=submission.id) }}" role="button" class="btn btn-outline-primary">Upload</a>
                <a href="{{ url_for('competition.submission_delete', comp_id=submission.comp_id, cat_id=cat_id, sub_id=submission.id) }}" role="button" class="btn btn-outline-danger">Delete</a>
        </div></div>
        {% elif user.reviewer == 1 %}
        <div class="col">
            <div class="btn-group" role="group" aria-label="Vote">
                <a href="{{ url_for('competition.submission_voting', comp_id=submission.comp_id, cat_id=cat_id, sub_id=submission.id) }}" role="button" class="btn btn-outline-primary">Vote</a>
        </div></div>
        {% endif %}
    </div>
{% endblock %}

app/templates/competition/submissionCategoryEdit.html
{% extends "base.html" %}

{% block app_content %}
    {% include '_form.html' %}
{% endblock %}

app/templates/competition/submissionVotesOverview.html
{% extends "base.html" %}

{% block app_content %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ url_for('competition.competitions_overview') }}">Competitions</a></li>
        <li class="breadcrumb-item"><a href="{{ url_for('competition.categories_overview', comp_id=comp_id) }}">{{ comp_name }}</a></li>
        <li class="breadcrumb-item"><a href="{{ url_for('competition.submissions_overview', comp_id=comp_id, cat_id=cat_id) }}">{{ cat_name }}</a></li>
        <li class="breadcrumb-item"><a href="{{ url_for('competition.submission_page', comp_id=comp_id, cat_id=cat_id, sub_id=sub_id) }}">{{ sub_name }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">Uploads</li>
        </ol>
    </nav>
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link" id="submission-tab" href="{{ url_for('competition.submission_page', comp_id=comp_id, cat_id=cat_id, sub_id=sub_id) }}">
                Submission
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="uploads-tab" href="{{ url_for('competition.submission_files', comp_id=comp_id, cat_id=cat_id, sub_id=sub_id) }}">
                Uploads
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" id="votes-overview-tab" href="{{ url_for('competition.submission_vote_overviewer', comp_id=comp_id, cat_id=cat_id, sub_id=sub_id) }}">
                Votes Overview
            </a>
        </li>
    </ul>
    <br>
    <h1>Votes Overview</h1>
    <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Score (/10)</th>
            <th scope="col">Comments</th>
            <th scope="col">Reviewer</th>
          </tr>
        </thead>
        <tbody>
            {% for vote in votes %}
                <tr>
                    <th scope="row">{{ loop.index }}</th>
                    <td>{{ vote.score }}</td>
                    <td>{{ vote.comments }}</td>
                    <td><a class="text-reset" href="{{ url_for('user.user_profile', username=vote.username) }}">{{ vote.reviewer_name }}</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

app/templates/competition/submissionVoting.html
{% extends "base.html" %}
{% import '_wtf.html' as wtf %}

{% block app_content %}
    <div class="row">
        <div class="col-md-4">
            <h1>{{ submission.name }} - {{ title }}</h1>
            {{ wtf.quick_form(form) }}
        </div>
        <div class="col">
            <h3>Category</h3>
            <h5>{{ cat.name }}</h5>
            <p class="font-weight-light">{{ cat.body }}</p>
        </div>
    </div>
{% endblock %}